### ISSUE TITLE
Analyse énergétique du robot pour alimentation batterie

### ISSUE THREAD

**Issue by charlesvuong-udes** [olivierfournier2/S4H2021-QuadrUS#11]
- [ ] Dimensionner le battery pack
- [ ] Choisir le pack à acheter
- [ ] Acheter le battery pack

**Comment by charlesvuong-udes** [comment]
Selon l'analyse, pour une autonomie de 30 minutes, une batterie de 6000mAh et 6V en sortie (ou plus, mais besoin d'une step-down converter) serait suffisante

**Comment by AnthonyBreton** [comment]
Les moteurs on un stall current d'environ 2A. Si on peut les alimenter à 6.8V, ça serait idéal, mais sinon 6V ferait la job. À 12 moteurs qui peuvent tirer jusqu'à 2A il faut un power supply d'au moins 15A.

**Comment by AnthonyBreton** [comment]
[Buck converter DC-DC input : 6V-40V / output : 1.2V-35V](https://www.amazon.ca/-/fr/dalimentation-convertisseur-Adaptateur-Constante-Convertisseur/dp/B0819Y8PJZ/ref=sr_1_20?adgrpid=65582528534&dchild=1&gclid=Cj0KCQiAmfmABhCHARIsACwPRAAf2ROnvWjbY95NNsEni2g6CQT8TYSHAddWwiS_xPJhAm4IMUhWkL8aAmhlEALw_wcB&hvadid=338531185890&hvdev=c&hvlocphy=1002632&hvnetw=g&hvqmt=b&hvrand=11819814698903336920&hvtargid=kwd-297012093113&hydadcr=10583_11072883&keywords=buck+converter+module&qid=1612670120&sr=8-20&tag=googlefrenchd-20)

**Comment by charlesvuong-udes** [comment]
- Une analyse a été faite pour l'alimentation filaire. On pourrait acheter un power supply (style power supply d'imprimante 3D) qui fourni 12V et a un courant max de 20A.
- À vérifier: réglementation du power supply, CSA, ULC, etc.


- L'option de power supply (style chargeur d'ordinateur portable) n'offre pas beaucoup de choix si on veut fournir jusqu'à 20A. Il y en a de 12V et 10A.

- Dans tous les cas, il est fort probable qu'il va falloir s'acheter un [step-down converter](https://www.amazon.ca/-/fr/dalimentation-convertisseur-Adaptateur-Constante-Convertisseur/dp/B0819Y8PJZ/ref=sr_1_20?adgrpid=65582528534&dchild=1&gclid=Cj0KCQiAmfmABhCHARIsACwPRAAf2ROnvWjbY95NNsEni2g6CQT8TYSHAddWwiS_xPJhAm4IMUhWkL8aAmhlEALw_wcB&hvadid=338531185890&hvdev=c&hvlocphy=1002632&hvnetw=g&hvqmt=b&hvrand=11819814698903336920&hvtargid=kwd-297012093113&hydadcr=10583_11072883&keywords=buck+converter+module&language=en_CA&qid=1612670120&sr=8-20&tag=googlefrenchd-20&th=1) pour réduire la tension en entrée des moteurs, car il n'y a pas de power supply qui fourni 6.8V à 20A max.
- Vérifier si le step-down converti la tension en courant ou s'il ne fait que dissiper toute l'énergie. Avec un step-down qui converti la tension en courant, il y aura moins de perte.

- Lorsqu'on aura une meilleure idée de la consommation de courant des 12 moteurs en fonctionnement normal, on pourra dimensionner une batterie en conséquence.
- Pour une batterie, il faut faire un protocol au Studio pour pouvoir le manipuler là-bas
