### ISSUE TITLE
Faire les tutoriels pour ROS et Gazebo

### ISSUE THREAD

**Issue by charlesvuong-udes** [olivierfournier2/S4H2021-QuadrUS#14]

**Comment by mathiasbourgault** [comment]
ROS training + pc setup : https://industrial-training.readthedocs.io/en/latest/index.html
Livres sur ROS : dans fichiers sur Teams (ressource principale)
Gazebo tutorials : http://gazebosim.org/tutorials

Installation de ROS Noetic on Pi 4 : https://varhowto.com/install-ros-noetic-raspberry-pi-4/#ROS_Noetic_Raspberry_Pi
