### ISSUE TITLE
Sélection des moteurs

### ISSUE THREAD

**Issue by charlesvuong-udes** [olivierfournier2/S4H2021-QuadrUS#7]
- [x] Dimensionnement des moteurs
- [x] Choix des moteurs
- [ ] Achats des moteurs

Recherche sur les différentes possibilités

**Comment by AnthonyBreton** [comment]
#### Moteur Dynamixel AX-12A pack de 6
https://emanual.robotis.com/docs/en/dxl/ax/ax-12a/ -> specsheet
- 224,50$ USD -> 309,25$ CAD
- Stall Torque 1,5 N*m
#### Moteur Dynamixel XL430-W250-T **2 prêté par l'uni**
https://www.robotis.us/dynamixel-xl430-w250-t/ -> specsheet
- Stall Torque 1,5 N*m donc le même que pour les AX-12A
On pourrait prendre 8 moteurs pour faire le robot et donc avoir seulement le pack de 6 à acheter. Voir l'image pour 2 moteurs par pattes. (Aucun moteur au niveau du genous, rotation faite par transmission de mouvement)
![image.png](https://images.zenhubusercontent.com/6008501ba918c9d79e89f146/46bc83b6-f87a-42d2-99b6-e308e7755dba)

**Comment by AnthonyBreton** [comment]
Voir le document word sur team **Choix des moteurs** path -> Général/Documentation
Document excel **Analyse des forces** à la même place

**Comment by charlesvuong-udes** [comment]
Lien vers le paquet de 4 moteurs
https://www.amazon.ca/-/fr/servomoteurs-num%C3%A9riques-%C3%A9tanches-DS3225-servomoteur/dp/B088GV6VND/ref=nav_signin?__mk_fr_CA=%C3%85M%C3%85%C5%BD%C3%95%C3%91&dchild=1&keywords=servo+25k+domains&qid=1611441988&s=toys&sr=1-25& 
Lien vers le paquet de 2 moteurs s'il en manque des 4
https://www.amazon.ca/-/fr/Update-DS3225-servomoteurs-num%C3%A9riques-%C3%A9tanches/dp/B088GYGYTD/ref=sr_1_14?__mk_fr_CA=%C3%85M%C3%85%C5%BD%C3%95%C3%91&dchild=1&keywords=servo+25k+domains&qid=1611441988&s=toys&sr=1-14

**Comment by AnthonyBreton** [comment]
Library Arduino pour contrôler les servos https://www.arduino.cc/reference/en/libraries/servo/
